package com.github.lindsaygelle.dqbs

enum class Attribute {
    AGILITY,
    MAGIC_POINTS,
    SLEEP_REQUIREMENT_MAXIMUM,
    SLEEP_REQUIREMENT_MINIMUM,
    SLEEP_RESISTANCE_MAXIMUM,
    SLEEP_RESISTANCE_MINIMUM,
    STOP_SPELL_REQUIREMENT_MAXIMUM,
    STOP_SPELL_REQUIREMENT_MINIMUM,
    STOP_SPELL_RESISTANCE_MAXIMUM,
    STOP_SPELL_RESISTANCE_MINIMUM,
    STRENGTH,
}